import { PdfDocument } from '../types';

export const INITIAL_FALLBACK_PDFS: PdfDocument[] = [
  {
    id: "civil-services-gs-paper-1-prep-guide",
    title: "Civil Services GS Paper I Preparation Guide",
    description: "Detailed syllabus study guide tailored specifically for civil services aspirants preparing for General Studies Paper I. Contains essential chapter outlines, practice booklets, historic distribution graphs, and tips from top educators.",
    fileSize: "4.8 MB",
    pageCount: 124,
    category: "Study Notes",
    tags: ["civil-services", "prelims", "gs-paper-1", "history", "polity"],
    thirdPartyViewUrl: "https://drive.google.com/file/d/1vGg-N4JcWvXwOnpndxY57oK_c4lE6H6z/view?usp=sharing",
    thirdPartyDownloadUrl: "https://drive.google.com/uc?export=download&id=1vGg-N4JcWvXwOnpndxY57oK_c4lE6H6z",
    coverUrl: "https://images.unsplash.com/photo-1506784983877-45594efa4cbe?auto=format&fit=crop&q=80&w=600",
    clickCount: 185,
    downloadCount: 74,
    createdBy: "google_admin",
    creatorEmail: "vaidwanprince@gmail.com",
    createdAt: new Date().toISOString()
  },
  {
    id: "upsc-ias-main-exam-optional-syllabus",
    title: "UPSC IAS Main Exam Optional Syllabus Outline",
    description: "Official complete structural review of the IAS mains examination options. Great search engine reference explaining qualifying paper rules, combinations lists, and step-by-step scoring strategies.",
    fileSize: "1.2 MB",
    pageCount: 35,
    category: "Syllabus & Curriculum",
    tags: ["upsc", "ias", "syllabus", "optional-subject"],
    thirdPartyViewUrl: "https://drive.google.com/file/d/1_o3rW1lU53vH1gX85W3pZc6v9B_98C3_/view?usp=sharing",
    thirdPartyDownloadUrl: "https://drive.google.com/uc?export=download&id=1_o3rW1lU53vH1gX85W3pZc6v9B_98C3_",
    coverUrl: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&q=80&w=600",
    clickCount: 142,
    downloadCount: 52,
    createdBy: "google_admin",
    creatorEmail: "vaidwanprince@gmail.com",
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString()
  },
  {
    id: "mock-exam-paper-general-aptitude-2026",
    title: "Mock Exam Paper - General Aptitude & CSAT 2026",
    description: "Full mock evaluation test with fully worked configurations, covering modern Quantitative Aptitude, logical deduction, reading comprehension, and problem solving matrices. Essential practice guide.",
    fileSize: "2.1 MB",
    pageCount: 40,
    category: "Exam Series",
    tags: ["mock-test", "aptitude", "csat", "reasoning"],
    thirdPartyViewUrl: "https://drive.google.com/file/d/1-uP_N4JcWvXwOnpndxY57oK_c4lE6H6z/view?usp=sharing",
    thirdPartyDownloadUrl: "https://drive.google.com/uc?export=download&id=1-uP_N4JcWvXwOnpndxY57oK_c4lE6H6z",
    coverUrl: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&q=80&w=600",
    clickCount: 228,
    downloadCount: 96,
    createdBy: "google_admin",
    creatorEmail: "vaidwanprince@gmail.com",
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString()
  },
  {
    id: "general-science-and-technology-handbook",
    title: "General Science & Technology Handbook",
    description: "Comprehensive study book and compendium detailing Space exploration milestones, cybersecurity defense architectures, biotechnology advances, and general Physics/Chemistry topics tested on modern Competitive Exams.",
    fileSize: "8.5 MB",
    pageCount: 210,
    category: "E-Books & Competitions",
    tags: ["general-science", "physics", "tech", "handbook"],
    thirdPartyViewUrl: "https://drive.google.com/file/d/1xFg-N4JcWvXwOnpndxY57oK_c4lE6H6z/view?usp=sharing",
    thirdPartyDownloadUrl: "https://drive.google.com/uc?export=download&id=1xFg-N4JcWvXwOnpndxY57oK_c4lE6H6z",
    coverUrl: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&q=80&w=600",
    clickCount: 310,
    downloadCount: 154,
    createdBy: "google_admin",
    creatorEmail: "vaidwanprince@gmail.com",
    createdAt: new Date(Date.now() - 86400000 * 10).toISOString()
  }
];
